---
dependencies:
  - {role: python3, when: "install_python and custom_repo"}
# - {role: python-build, when: "not custom_repo"}
  - role: postgresql-client7
  - role: openjdk1.8
  - {role: epel7, when: "use_epel and not 'production' in group_names"}
  - role: odbc7
  - role: jdbc
