# main.yml - Install Python 3.4 from a repo
---
- name: Ensure EPEL Latest is Installed for Python34
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install Python34 packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python34
    - python34-setuptools
    - python34-devel
  tags:
    - python3

- name: Install pip
  easy_install:
    name: pip
    executable: easy_install-3.4
  tags:
    - python3
